# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-amd64"
    use: buildx
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: "ghcr.io/southclaws/restic-robot:{{ .Version }}"
    image_templates:
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-amd64"
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/southclaws/restic-robot:latest"
    image_templates:
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-amd64"
      - "ghcr.io/southclaws/restic-robot:{{ .Version }}-arm64v8"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
